default['tiger_sec']['test_attributes_hash']={
  "name"=>"Docker container ID",
  "tests_type"=>"Security test type",
  "tiger_env_type" => "TIGER environment type",
  "env_type"=>"Environment type",
  "build_number"=>"Build ID",
  "sol_ext_name"=>"SID extension",
  "safe_pipeline"=>"Safe pipeline mode enabled",
  "instance_hw_type"=>"Docker container type",
  "lg_count"=>"Load generators count",
  "target_host"=>"Target host",
  "target_port"=>"Target port",
  "protocol"=>"Used protocol",
  "comment"=>"Comment",
  "check_logjam"=>"LogJam vulnerabilities checks enabled",
  "permitted_ports"=>"Permitted ports",
  "ignore_certs_trusts"=>"Ignore certificates trusts chanins",
  "unicornscan_cmd_params" => "Unicornscan command line arguments",
  "nmap_cmd_params" => "Nmap command line arguments",
  "nikto_cmd_params" => "Nikto command line arguments",
  "w3af_file_name" => "W3AF command file name",
  "ports_to_scan"=>"Ports range to scan",
  "qualys_scanner"=>"Qualys WAS scanner appliance",
  "qualys_profile_id"=>"Qualys WAS option profile id",
  "qualys_template_id"=>"Qualys WAS report template id",
  "burp_excluded_ext"=>"Burp excluded extensions"
}

